### ISSUE TITLE
Help button should open new tab instead of wiping content

### ISSUE THREAD

**Issue by Cabalist** [prahladyeri/valchemist#10]
Just a usability request.

Currently when you click "Help" it is a direct link to github page.  This wipes out all of the content that you have created.  The "Help" link should open a new tab instead or at least warn of this behaviour.

**Comment by prahladyeri** [comment]
@Cabalist  Thanks a lot for contributing. I'm working on this issue.

**Comment by prahladyeri** [comment]
This is fixed. The help button now opens a small popup and gives a brief explanation of what the other buttons do. Please test and let me know.

**Comment by Cabalist** [comment]
Works for me. Thanks!
