### ISSUE TITLE
Not able to delete tables

### ISSUE THREAD

**Issue by lhausmann** [prahladyeri/valchemist#13]
Hey,
using  43.0.2357.130 under MacOS 10.10.3 I'm not able to delete tables.

**Comment by prahladyeri** [comment]
Did you try clicking the red button with cross symbol on top-right corner? That is the icon for deleting the table.

And 43.0 version of what? Safari/Chrome/Firefox?

**Comment by lhausmann** [comment]
Oh, sorry, that's under Chrome 43 and yes, I tried clicking the cross symbol button.

**Comment by jayeshcp** [comment]
Tested on Chrome version 43.0.2357.134 m on Windows 8. It works perfectly fine.

**Comment by prahladyeri** [comment]
@jayeshcp Thanks for the confirmation. I'm closing this.
