### ISSUE TITLE
Needs a way to add foreign keys

### ISSUE THREAD

**Issue by Euphorbium** [prahladyeri/valchemist#2]

**Comment by prahladyeri** [comment]
@Euphorbium  Thanks a lot for contributing to Visual Alchemist. I'm working on the fix for this.

**Comment by prahladyeri** [comment]
Hey, this is fixed. Please test and let me know.

**Comment by shearichard** [comment]
@prahladyeri : Thanks for making this change. I was interested to try it out on the demo at : http://valchemist-inn.rhcloud.com/ but I couldn't see any reference to it. Is that because http://valchemist-inn.rhcloud.com/ runs something other than HEAD or is there just something I'm not seeing ?
